name: docker image build and push
on:
  push:
    branches:
      - 'master'
    paths:
      - 'Dockerfile'

env:
  REGION_ID: 'ap-southeast-3'
  SWR_ORGANIZATION:  'public-base'
  IMAGE_NAME: 'net-box'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.SWR_ACCESSKEY }}
          access-key-secret: ${{ secrets.SWR_SECRETACCESSKEY }}
          region: ${{ env.REGION_ID }}
